rust-teos: remove deprecated python-teos submodule, use rust-teos instead
lightningd/plugins pull request #478
Opened 2023-10-15 20:58 UTC by seberm

Remove the `python-teos` submodule and replace it by `watchtower` which links to [rust-teos](https://github.com/talaia-labs/rust-teos).

See (https://github.com/talaia-labs/python-teos#state-of-the-project):

> This codebase has been discontinued in favour of its rust counterpart. Please, do check [the new codebase](https://github.com/talaia-labs/rust-teos).

See also: 5f656a1f0f37fa8b431efb248127d221ad9faf8d - Replaces python-teos by rust-teos

2024-02-07 12:45 UTC, vincenzopalazzo approved these changes

2024-02-07 15:35 UTC, chrisguida submitted a review, later dismissed
Needs rebase

2024-02-07 15:35 UTC, chrisguida commented on .gitmodules
> +[submodule "watchtower"]
Why "watchtower"? Seems the name should be "rust-teos", no?

2024-02-07 15:35 UTC, chrisguida commented on README.md
> -| [python-teos][python-teos]           | The Eye of Satoshi - Lightning Watchtower                                                   |
We should add the new repo to the README

2024-02-07 15:35 UTC, chrisguida commented on README.md
> -[python-teos]: https://github.com/talaia-labs/python-teos
Same here

2024-02-13 15:49 UTC, chrisguida commented on README.md
> +| [python-teos][python-teos]           | Old Python implementation of The Eye of Satoshi - Lightning Watchtower                      |
Please alphabetize

2024-02-13 15:49 UTC, chrisguida commented on README.md
> +[rust-teos]: https://github.com/talaia-labs/rust-teos/tree/master/watchtower-plugin
don't rename this, `watchtower-client` is the name of the plugin

2024-02-13 15:57 UTC, chrisguida commented on README.md
> +[rust-teos]: https://github.com/talaia-labs/rust-teos/tree/master/watchtower-plugin
This also breaks the link and looks super weird
![Screenshot from 2024-02-13 09-46-42](https://github.com/lightningd/plugins/assets/7445670/4674b8d0-93b4-43be-bbcd-fcfd0622c238)

Just revert this change

2024-02-13 15:59 UTC, chrisguida commented on README.md
> +| [rust-teos][rust-teos]               | The Eye of Satoshi - Lightning Watchtower (the [watchtower-plugin](https://github.com/talaia-labs/rust-teos/tree/master/watchtower-plugin) subdirectory)  |
Just remove this, the watchtower plugin is already in the list. Also rust-teos isn't a plugin.

https://github.com/lightningd/plugins/pull/478/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R39

2024-02-13 16:00 UTC, chrisguida commented on README.md
> +| [rust-teos][rust-teos]               | The Eye of Satoshi - Lightning Watchtower (the [watchtower-plugin](https://github.com/talaia-labs/rust-teos/tree/master/watchtower-plugin) subdirectory)  |
Also I would change line 39 from 

`[watchtower][watchtower-client]` to `[watchtower-client][watchtower-client]`

2024-02-13 16:02 UTC, chrisguida requested changes
Neither `rust-teos` nor `python-teos` are plugins, let's just remove them.

`watchtower-client` is already on the list, just keep it as is except call it `watchtower-client` where it's currently `watchtower`

2024-04-12 08:44 UTC, vincenzopalazzo approved these changes
ACK 5eea140cf8e7a3a6e36e0dd3fe1c446e0b586039

I vote in favor to have `watchtower-client` to have in, also `rust-teos` was a good name but nevermind it is a minors things

2024-04-12 08:58 UTC, merged

2024-04-16 23:16 UTC, chrisguida commented
Looks great, thanks @seberm !

@vincenzopalazzo looks like you can merge things!