Update backup/README.md
lightningd/plugins pull request #479
Opened 2023-10-17 09:03 UTC by LeoSpyke

Fix a dead link to "info about backup solutions"

2024-02-07 15:32 UTC, chrisguida commented
Needs rebase

2024-02-12 20:53 UTC, chrisguida submitted a review, later dismissed

2024-02-12 20:53 UTC, chrisguida commented on backup/README.md
> +Related info about backup solutions: https://github.com/ElementsProject/lightning/blob/master/doc/beginners-guide/backup-and-recovery.md
This link appears to be broken as well

2024-02-21 17:32 UTC, chrisguida commented
Can you clean up the commit history here? For some reason there are 5 commits, there needs to be just 1 commit with your change. I tried to merge master into your branch but it did not fix the problem, sorry.

2024-02-21 17:33 UTC, chrisguida requested changes
needs history cleanup

2024-03-04 10:46 UTC, cdecker commented
Contributor does not allow maintainers to amend the PR. As such we need them to rebase in order to be merged. If the author does not, I will just cherry-pick the one useful commit onto a fixup PR later.

2024-06-04 00:31 UTC, closed without merging