Add file permission notes to readme
lightningd/plugins pull request #579
Opened 2024-08-05 07:54 UTC by Jhoyola

2024-08-06 16:29 UTC, chrisguida commented on README.md
> +   - You must have git core.fileMode set to true to reflect the permissons in git
```suggestion
   - You must have git core.fileMode set to true to reflect the permissions in git
```

2024-08-06 16:30 UTC, chrisguida requested changes
see misspelling

2024-08-06 16:32 UTC, chrisguida commented
Please squash

2024-08-06 16:33 UTC, Jhoyola commented
I'll squash tomorrow 👍

2024-08-20 18:33 UTC, chrisguida approved these changes
ACK https://github.com/lightningd/plugins/commit/52400a86b17b2cc87f3c094285daf6b6119de335

2024-08-20 18:51 UTC, chrisguida commented
I don't know why but this PR seems to be stuck "processing updates"

![image](https://github.com/user-attachments/assets/addc3d57-6561-4334-84f5-0f99eeaa55dc)

Turned on automerge to try to see if it will merge itself once it gets unstuck

2024-08-21 19:18 UTC, chrisguida commented
Yep haha

I guess just some random bug in GH

re-ACK https://github.com/lightningd/plugins/pull/579/commits/d47003aa8ae308931d5895d36efd6fa3f7562456

2024-08-21 19:18 UTC, merged